modLoader="javafml" #mandatory
loaderVersion="[30,)" #mandatory (28 is current forge version)
credits=""
authors="MaroonShaded, Rovetown and Velocityraptor"

[[mods]] #mandatory
modId="testmod" #mandatory
version="1.0" #mandatory
displayName="Test Mod" #mandatory
description='''
Modding. That's it.
'''

[[dependencies.testmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[30,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.tutorialmod]]
	modId="minecraft"
	mandatory=true
	versionrange="[1.15.1]"
	ordering="NONE"
	side="BOTH"