modLoader="javafml"
loaderVersion="[31,)"
# issueTrackerURL=""
[[mods]]
modId="testmod"
version="${file.jarVersion}"
displayName="Test Mod"
# updateJSONURL=""
# displayURL=""
logoFile="testmod.png"
credits="Velocityraptor, Rovetown and Maroonshaded"
authors="Velocityraptor, Rovetown and Maroonshaded"
description='''
This is a mod made by Velocityraptor, Maroonshaded and Rovetown
'''
[[dependencies.testmod]]
    modId="forge"
    mandatory=true
    versionRange="[31,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.testmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
